# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kevin\Documents\docss\Cuatrimaterias\programacion\Proga 2\tresPatitosUIA\src\062_reporte_bienes_no_asignables.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportBienesNoAsignables(object):
    def setupUi(self, ReportBienesNoAsignables):
        ReportBienesNoAsignables.setObjectName("ReportBienesNoAsignables")
        ReportBienesNoAsignables.resize(552, 423)
        ReportBienesNoAsignables.setMinimumSize(QtCore.QSize(552, 423))
        ReportBienesNoAsignables.setMaximumSize(QtCore.QSize(552, 423))
        font = QtGui.QFont()
        font.setPointSize(14)
        ReportBienesNoAsignables.setFont(font)
        self.tblWidgetBienesNoAsignados = QtWidgets.QTableWidget(ReportBienesNoAsignables)
        self.tblWidgetBienesNoAsignados.setGeometry(QtCore.QRect(40, 80, 461, 171))
        self.tblWidgetBienesNoAsignados.setFrameShape(QtWidgets.QFrame.Box)
        self.tblWidgetBienesNoAsignados.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tblWidgetBienesNoAsignados.setLineWidth(3)
        self.tblWidgetBienesNoAsignados.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblWidgetBienesNoAsignados.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblWidgetBienesNoAsignados.setObjectName("tblWidgetBienesNoAsignados")
        self.tblWidgetBienesNoAsignados.setColumnCount(5)
        self.tblWidgetBienesNoAsignados.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblWidgetBienesNoAsignados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblWidgetBienesNoAsignados.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblWidgetBienesNoAsignados.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblWidgetBienesNoAsignados.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblWidgetBienesNoAsignados.setHorizontalHeaderItem(4, item)
        self.lblReportBienesNoAsignables = QtWidgets.QLabel(ReportBienesNoAsignables)
        self.lblReportBienesNoAsignables.setGeometry(QtCore.QRect(120, 20, 291, 41))
        self.lblReportBienesNoAsignables.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblReportBienesNoAsignables.setObjectName("lblReportBienesNoAsignables")
        self.bttBienesNoAsignables = QtWidgets.QPushButton(ReportBienesNoAsignables)
        self.bttBienesNoAsignables.setGeometry(QtCore.QRect(190, 330, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bttBienesNoAsignables.setFont(font)
        self.bttBienesNoAsignables.setObjectName("bttBienesNoAsignables")

        self.retranslateUi(ReportBienesNoAsignables)
        QtCore.QMetaObject.connectSlotsByName(ReportBienesNoAsignables)

    def retranslateUi(self, ReportBienesNoAsignables):
        _translate = QtCore.QCoreApplication.translate
        ReportBienesNoAsignables.setWindowTitle(_translate("ReportBienesNoAsignables", "Reporte de bienes no Asignables"))
        item = self.tblWidgetBienesNoAsignados.horizontalHeaderItem(0)
        item.setText(_translate("ReportBienesNoAsignables", "Placa"))
        item = self.tblWidgetBienesNoAsignados.horizontalHeaderItem(1)
        item.setText(_translate("ReportBienesNoAsignables", "Nombre"))
        item = self.tblWidgetBienesNoAsignados.horizontalHeaderItem(2)
        item.setText(_translate("ReportBienesNoAsignables", "Categoria"))
        item = self.tblWidgetBienesNoAsignados.horizontalHeaderItem(3)
        item.setText(_translate("ReportBienesNoAsignables", "Descripcion"))
        item = self.tblWidgetBienesNoAsignados.horizontalHeaderItem(4)
        item.setText(_translate("ReportBienesNoAsignables", "Estado"))
        self.lblReportBienesNoAsignables.setText(_translate("ReportBienesNoAsignables", "Reporte de Bienes no Asignables"))
        self.bttBienesNoAsignables.setText(_translate("ReportBienesNoAsignables", "Obtener Bienes no Asignados"))
