# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\aaron\OneDrive\Documentos\Python\tresPatitosUIA\src\051_asignacion_bienes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Asignacion(object):
    def setupUi(self, Asignacion):
        Asignacion.setObjectName("Asignacion")
        Asignacion.setEnabled(True)
        Asignacion.resize(700, 570)
        Asignacion.setMinimumSize(QtCore.QSize(700, 570))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\aaron\\OneDrive\\Documentos\\Python\\tresPatitosUIA\\src\\../res/iconAsignar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Asignacion.setWindowIcon(icon)
        Asignacion.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.tblAsignados = QtWidgets.QTableWidget(Asignacion)
        self.tblAsignados.setGeometry(QtCore.QRect(40, 300, 431, 192))
        self.tblAsignados.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tblAsignados.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblAsignados.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tblAsignados.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblAsignados.setObjectName("tblAsignados")
        self.tblAsignados.setColumnCount(4)
        self.tblAsignados.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblAsignados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAsignados.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAsignados.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAsignados.setHorizontalHeaderItem(3, item)
        self.labelHeader = QtWidgets.QLabel(Asignacion)
        self.labelHeader.setGeometry(QtCore.QRect(20, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.labelHeader.setFont(font)
        self.labelHeader.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"background-color: rgba(0,0,0,0%);")
        self.labelHeader.setText("")
        self.labelHeader.setPixmap(QtGui.QPixmap("c:\\Users\\aaron\\OneDrive\\Documentos\\Python\\tresPatitosUIA\\src\\../res/assign.png"))
        self.labelHeader.setScaledContents(True)
        self.labelHeader.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelHeader.setObjectName("labelHeader")
        self.lbl_departamentos = QtWidgets.QLabel(Asignacion)
        self.lbl_departamentos.setGeometry(QtCore.QRect(60, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(5)
        self.lbl_departamentos.setFont(font)
        self.lbl_departamentos.setStyleSheet("font: 43 10pt \"Segoe UI Semibold\";\n"
"border:none;\n"
"background-color: rgba(0,0,0,0%);")
        self.lbl_departamentos.setObjectName("lbl_departamentos")
        self.frame = QtWidgets.QFrame(Asignacion)
        self.frame.setGeometry(QtCore.QRect(40, 60, 431, 181))
        self.frame.setToolTip("")
        self.frame.setToolTipDuration(-1)
        self.frame.setStyleSheet("border:4px solid;\n"
"border-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lblCedula = QtWidgets.QLabel(self.frame)
        self.lblCedula.setGeometry(QtCore.QRect(50, 20, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lblCedula.setFont(font)
        self.lblCedula.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"border:none;")
        self.lblCedula.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCedula.setObjectName("lblCedula")
        self.lblNombre = QtWidgets.QLabel(self.frame)
        self.lblNombre.setGeometry(QtCore.QRect(50, 50, 50, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lblNombre.setFont(font)
        self.lblNombre.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"border:none;")
        self.lblNombre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblNombre.setObjectName("lblNombre")
        self.txtNombre = QtWidgets.QLineEdit(self.frame)
        self.txtNombre.setGeometry(QtCore.QRect(110, 50, 121, 20))
        self.txtNombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtNombre.setObjectName("txtNombre")
        self.lbl_codigo_2 = QtWidgets.QLabel(self.frame)
        self.lbl_codigo_2.setGeometry(QtCore.QRect(240, 20, 121, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_codigo_2.sizePolicy().hasHeightForWidth())
        self.lbl_codigo_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lbl_codigo_2.setFont(font)
        self.lbl_codigo_2.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"border:none;\n"
"")
        self.lbl_codigo_2.setText("")
        self.lbl_codigo_2.setPixmap(QtGui.QPixmap("c:\\Users\\aaron\\OneDrive\\Documentos\\Python\\tresPatitosUIA\\src\\../res/icons8-stacked-organizational-chart-highlighted-parent-node-96.png"))
        self.lbl_codigo_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_codigo_2.setObjectName("lbl_codigo_2")
        self.lblTelefono = QtWidgets.QLabel(self.frame)
        self.lblTelefono.setGeometry(QtCore.QRect(40, 80, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lblTelefono.setFont(font)
        self.lblTelefono.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"border:none;")
        self.lblTelefono.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTelefono.setObjectName("lblTelefono")
        self.txtTelefono = QtWidgets.QLineEdit(self.frame)
        self.txtTelefono.setGeometry(QtCore.QRect(110, 80, 121, 20))
        self.txtTelefono.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtTelefono.setObjectName("txtTelefono")
        self.lblBienAsignado = QtWidgets.QLabel(self.frame)
        self.lblBienAsignado.setGeometry(QtCore.QRect(10, 140, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lblBienAsignado.setFont(font)
        self.lblBienAsignado.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"border:none;")
        self.lblBienAsignado.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblBienAsignado.setObjectName("lblBienAsignado")
        self.cbxBienes = QtWidgets.QComboBox(self.frame)
        self.cbxBienes.setEnabled(True)
        self.cbxBienes.setGeometry(QtCore.QRect(110, 140, 121, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxBienes.sizePolicy().hasHeightForWidth())
        self.cbxBienes.setSizePolicy(sizePolicy)
        self.cbxBienes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbxBienes.setEditable(False)
        self.cbxBienes.setCurrentText("")
        self.cbxBienes.setObjectName("cbxBienes")
        self.cbxCedulaEmpleados = QtWidgets.QComboBox(self.frame)
        self.cbxCedulaEmpleados.setEnabled(True)
        self.cbxCedulaEmpleados.setGeometry(QtCore.QRect(110, 20, 121, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxCedulaEmpleados.sizePolicy().hasHeightForWidth())
        self.cbxCedulaEmpleados.setSizePolicy(sizePolicy)
        self.cbxCedulaEmpleados.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbxCedulaEmpleados.setEditable(False)
        self.cbxCedulaEmpleados.setCurrentText("")
        self.cbxCedulaEmpleados.setObjectName("cbxCedulaEmpleados")
        self.btnLimpiar = QtWidgets.QPushButton(self.frame)
        self.btnLimpiar.setGeometry(QtCore.QRect(250, 140, 71, 21))
        self.btnLimpiar.setMaximumSize(QtCore.QSize(90, 30))
        self.btnLimpiar.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid #55C1FA;\n"
"border-radius:10px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\aaron\\OneDrive\\Documentos\\Python\\tresPatitosUIA\\src\\../res/btnClear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLimpiar.setIcon(icon1)
        self.btnLimpiar.setIconSize(QtCore.QSize(18, 18))
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.btnGuardar = QtWidgets.QPushButton(Asignacion)
        self.btnGuardar.setGeometry(QtCore.QRect(200, 260, 101, 31))
        self.btnGuardar.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid #55C1FA;\n"
"border-radius:10px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\aaron\\OneDrive\\Documentos\\Python\\tresPatitosUIA\\src\\../res/btnSave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGuardar.setIcon(icon2)
        self.btnGuardar.setIconSize(QtCore.QSize(20, 20))
        self.btnGuardar.setObjectName("btnGuardar")

        self.retranslateUi(Asignacion)
        QtCore.QMetaObject.connectSlotsByName(Asignacion)

    def retranslateUi(self, Asignacion):
        _translate = QtCore.QCoreApplication.translate
        Asignacion.setWindowTitle(_translate("Asignacion", "Asignacion de bienes"))
        item = self.tblAsignados.horizontalHeaderItem(0)
        item.setText(_translate("Asignacion", "Cédula"))
        item = self.tblAsignados.horizontalHeaderItem(1)
        item.setText(_translate("Asignacion", "Nombre"))
        item = self.tblAsignados.horizontalHeaderItem(2)
        item.setText(_translate("Asignacion", "Télefono"))
        item = self.tblAsignados.horizontalHeaderItem(3)
        item.setText(_translate("Asignacion", "Bien asignado"))
        self.lbl_departamentos.setText(_translate("Asignacion", "Registro de Bienes Asignados"))
        self.frame.setAccessibleDescription(_translate("Asignacion", "Generar código"))
        self.lblCedula.setText(_translate("Asignacion", "Cédula"))
        self.lblNombre.setText(_translate("Asignacion", "Nombre"))
        self.lblTelefono.setText(_translate("Asignacion", "Teléfono"))
        self.lblBienAsignado.setText(_translate("Asignacion", "Asignar bien:"))
        self.btnLimpiar.setToolTip(_translate("Asignacion", "CTRL+W"))
        self.btnLimpiar.setText(_translate("Asignacion", "Limpiar"))
        self.btnLimpiar.setShortcut(_translate("Asignacion", "Ctrl+W"))
        self.btnGuardar.setToolTip(_translate("Asignacion", "CTRL+S"))
        self.btnGuardar.setText(_translate("Asignacion", "Registrar"))
        self.btnGuardar.setShortcut(_translate("Asignacion", "Ctrl+C"))
