# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\aaron\OneDrive\Documentos\Python\tresPatitosUIA\src\063_ReporteEmpleados.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReporteEmpleados(object):
    def setupUi(self, ReporteEmpleados):
        ReporteEmpleados.setObjectName("ReporteEmpleados")
        ReporteEmpleados.resize(1057, 549)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReporteEmpleados.sizePolicy().hasHeightForWidth())
        ReporteEmpleados.setSizePolicy(sizePolicy)
        ReporteEmpleados.setMinimumSize(QtCore.QSize(1020, 500))
        ReporteEmpleados.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.labelHeader = QtWidgets.QLabel(ReporteEmpleados)
        self.labelHeader.setGeometry(QtCore.QRect(40, 20, 261, 41))
        self.labelHeader.setStyleSheet("font: 43 10pt \"Segoe UI Semibold\";\n"
"border:none;\n"
"background-color: rgba(0,0,0,0%);")
        self.labelHeader.setObjectName("labelHeader")
        self.tblEmpleadosDepartamento = QtWidgets.QTableWidget(ReporteEmpleados)
        self.tblEmpleadosDepartamento.setGeometry(QtCore.QRect(50, 160, 450, 270))
        self.tblEmpleadosDepartamento.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tblEmpleadosDepartamento.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblEmpleadosDepartamento.setObjectName("tblEmpleadosDepartamento")
        self.tblEmpleadosDepartamento.setColumnCount(4)
        self.tblEmpleadosDepartamento.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblEmpleadosDepartamento.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEmpleadosDepartamento.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEmpleadosDepartamento.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEmpleadosDepartamento.setHorizontalHeaderItem(3, item)
        self.cmbBoxDepartamento = QtWidgets.QComboBox(ReporteEmpleados)
        self.cmbBoxDepartamento.setGeometry(QtCore.QRect(150, 80, 101, 22))
        self.cmbBoxDepartamento.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmbBoxDepartamento.setObjectName("cmbBoxDepartamento")
        self.labelDepartamentos = QtWidgets.QLabel(ReporteEmpleados)
        self.labelDepartamentos.setGeometry(QtCore.QRect(50, 80, 91, 16))
        self.labelDepartamentos.setStyleSheet("font: 43 10pt \"Segoe UI Semibold\";\n"
"border:none;\n"
"background-color: rgba(0,0,0,0%);")
        self.labelDepartamentos.setObjectName("labelDepartamentos")
        self.labelEmpleados = QtWidgets.QLabel(ReporteEmpleados)
        self.labelEmpleados.setGeometry(QtCore.QRect(50, 130, 71, 16))
        self.labelEmpleados.setStyleSheet("font: 43 10pt \"Segoe UI Semibold\";\n"
"border:none;\n"
"background-color: rgba(0,0,0,0%);")
        self.labelEmpleados.setObjectName("labelEmpleados")
        self.labelGrafico = QtWidgets.QLabel(ReporteEmpleados)
        self.labelGrafico.setGeometry(QtCore.QRect(510, 130, 271, 16))
        self.labelGrafico.setStyleSheet("font: 43 10pt \"Segoe UI Semibold\";\n"
"border:none;\n"
"background-color: rgba(0,0,0,0%);")
        self.labelGrafico.setObjectName("labelGrafico")
        self.btnExport = QtWidgets.QPushButton(ReporteEmpleados)
        self.btnExport.setGeometry(QtCore.QRect(50, 440, 75, 23))
        self.btnExport.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid #55C1FA;\n"
"border-radius:10px;\n"
"}")
        self.btnExport.setObjectName("btnExport")
        self.btnSearch = QtWidgets.QPushButton(ReporteEmpleados)
        self.btnSearch.setGeometry(QtCore.QRect(260, 80, 75, 23))
        self.btnSearch.setObjectName("btnSearch")
        self.graphicFrame = QtWidgets.QFrame(ReporteEmpleados)
        self.graphicFrame.setGeometry(QtCore.QRect(520, 160, 500, 300))
        self.graphicFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphicFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphicFrame.setObjectName("graphicFrame")

        self.retranslateUi(ReporteEmpleados)
        QtCore.QMetaObject.connectSlotsByName(ReporteEmpleados)

    def retranslateUi(self, ReporteEmpleados):
        _translate = QtCore.QCoreApplication.translate
        ReporteEmpleados.setWindowTitle(_translate("ReporteEmpleados", "Empleados por Departamento"))
        self.labelHeader.setText(_translate("ReporteEmpleados", "Empleados por Departamento"))
        self.tblEmpleadosDepartamento.setSortingEnabled(True)
        item = self.tblEmpleadosDepartamento.horizontalHeaderItem(0)
        item.setText(_translate("ReporteEmpleados", "Fecha de Ingreso"))
        item = self.tblEmpleadosDepartamento.horizontalHeaderItem(1)
        item.setText(_translate("ReporteEmpleados", "Cedula"))
        item = self.tblEmpleadosDepartamento.horizontalHeaderItem(2)
        item.setText(_translate("ReporteEmpleados", "Nombre"))
        item = self.tblEmpleadosDepartamento.horizontalHeaderItem(3)
        item.setText(_translate("ReporteEmpleados", "Puesto"))
        self.labelDepartamentos.setText(_translate("ReporteEmpleados", "Departamento"))
        self.labelEmpleados.setText(_translate("ReporteEmpleados", "Empleados"))
        self.labelGrafico.setText(_translate("ReporteEmpleados", "Cantidad de Empleados por Departamento"))
        self.btnExport.setText(_translate("ReporteEmpleados", "Export"))
        self.btnSearch.setText(_translate("ReporteEmpleados", "Search"))
