# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rviqu\OneDrive - Universidad Internacional de las Américas (UIA)\UIA\2024\I\Programación II\Proyecto Final\tresPatitosUIA\src\061_reporte_bienes_asignados.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReporteBienesAsignados(object):
    def setupUi(self, ReporteBienesAsignados):
        ReporteBienesAsignados.setObjectName("ReporteBienesAsignados")
        ReporteBienesAsignados.resize(397, 300)
        self.lblTitulo = QtWidgets.QLabel(ReporteBienesAsignados)
        self.lblTitulo.setGeometry(QtCore.QRect(50, 30, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        self.lblEmpleado = QtWidgets.QLabel(ReporteBienesAsignados)
        self.lblEmpleado.setGeometry(QtCore.QRect(50, 80, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblEmpleado.setFont(font)
        self.lblEmpleado.setObjectName("lblEmpleado")
        self.cbxSeleccionEmpleado = QtWidgets.QComboBox(ReporteBienesAsignados)
        self.cbxSeleccionEmpleado.setGeometry(QtCore.QRect(50, 110, 69, 22))
        self.cbxSeleccionEmpleado.setObjectName("cbxSeleccionEmpleado")
        self.tblReporteBienesAsignados = QtWidgets.QTableWidget(ReporteBienesAsignados)
        self.tblReporteBienesAsignados.setGeometry(QtCore.QRect(50, 150, 256, 121))
        self.tblReporteBienesAsignados.setObjectName("tblReporteBienesAsignados")
        self.tblReporteBienesAsignados.setColumnCount(0)
        self.tblReporteBienesAsignados.setRowCount(0)

        self.retranslateUi(ReporteBienesAsignados)
        QtCore.QMetaObject.connectSlotsByName(ReporteBienesAsignados)

    def retranslateUi(self, ReporteBienesAsignados):
        _translate = QtCore.QCoreApplication.translate
        ReporteBienesAsignados.setWindowTitle(_translate("ReporteBienesAsignados", "Reporte_Bienes_Asignados"))
        self.lblTitulo.setText(_translate("ReporteBienesAsignados", "Reporte Bienes Asignados por empleado"))
        self.lblEmpleado.setText(_translate("ReporteBienesAsignados", "Seleccione el empleado"))
