# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rviqu\OneDrive - Universidad Internacional de las Américas (UIA)\UIA\2024\I\Programación II\Proyecto Final\tresPatitosUIA\src\001_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 400)
        Login.setMinimumSize(QtCore.QSize(400, 400))
        Login.setMaximumSize(QtCore.QSize(400, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/iconMDI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        Login.setAutoFillBackground(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_widget = QtWidgets.QWidget(Login)
        self.login_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.login_widget.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.login_widget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStatesMinorOutlyingIslands))
        self.login_widget.setObjectName("login_widget")
        self.labelHeader = QtWidgets.QLabel(self.login_widget)
        self.labelHeader.setGeometry(QtCore.QRect(150, 40, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelHeader.setFont(font)
        self.labelHeader.setStyleSheet("")
        self.labelHeader.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Zimbabwe))
        self.labelHeader.setText("")
        self.labelHeader.setPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/iconLoginHeader.png"))
        self.labelHeader.setScaledContents(True)
        self.labelHeader.setObjectName("labelHeader")
        self.btn_login = QtWidgets.QPushButton(self.login_widget)
        self.btn_login.setGeometry(QtCore.QRect(140, 300, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_login.setStyleSheet("QPushButton{\n"
"background-color:rgb(85, 193, 250);\n"
"border:none;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(250, 250, 250);\n"
"border:3px solid #55C1FA;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/icons8-login-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_login.setIcon(icon1)
        self.btn_login.setIconSize(QtCore.QSize(20, 20))
        self.btn_login.setObjectName("btn_login")
        self.txt_password = QtWidgets.QLineEdit(self.login_widget)
        self.txt_password.setGeometry(QtCore.QRect(100, 210, 190, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_password.sizePolicy().hasHeightForWidth())
        self.txt_password.setSizePolicy(sizePolicy)
        self.txt_password.setFocusPolicy(QtCore.Qt.TabFocus)
        self.txt_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:3px solid #55C1FA;\n"
"border-radius:10px;")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_password.setClearButtonEnabled(False)
        self.txt_password.setObjectName("txt_password")
        self.txt_username = QtWidgets.QLineEdit(self.login_widget)
        self.txt_username.setGeometry(QtCore.QRect(100, 140, 190, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_username.sizePolicy().hasHeightForWidth())
        self.txt_username.setSizePolicy(sizePolicy)
        self.txt_username.setMinimumSize(QtCore.QSize(20, 5))
        self.txt_username.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txt_username.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:3px solid #55C1FA;\n"
"border-radius:10px;")
        self.txt_username.setText("")
        self.txt_username.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_username.setObjectName("txt_username")
        self.labelUsername = QtWidgets.QLabel(self.login_widget)
        self.labelUsername.setGeometry(QtCore.QRect(50, 130, 51, 41))
        self.labelUsername.setText("")
        self.labelUsername.setPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/iconLoginUsername.png"))
        self.labelUsername.setScaledContents(True)
        self.labelUsername.setObjectName("labelUsername")
        self.labelPassword = QtWidgets.QLabel(self.login_widget)
        self.labelPassword.setGeometry(QtCore.QRect(60, 210, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPassword.sizePolicy().hasHeightForWidth())
        self.labelPassword.setSizePolicy(sizePolicy)
        self.labelPassword.setStyleSheet("background-color: rgb(0, 0, 0,0%);")
        self.labelPassword.setText("")
        self.labelPassword.setPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/iconPassword.png"))
        self.labelPassword.setScaledContents(True)
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout.addWidget(self.login_widget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Log In"))
        self.labelHeader.setWhatsThis(_translate("Login", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Log In</span></p></body></html>"))
        self.btn_login.setText(_translate("Login", " Log in"))
        self.txt_password.setPlaceholderText(_translate("Login", "Password"))
        self.txt_username.setPlaceholderText(_translate("Login", "Username"))
