# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kevin\Documents\docss\Cuatrimaterias\programacion\Proga 2\tresPatitosUIA\src\060_reportes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reportes(object):
    def setupUi(self, Reportes):
        Reportes.setObjectName("Reportes")
        Reportes.setWindowModality(QtCore.Qt.WindowModal)
        Reportes.resize(695, 553)
        self.tabWidget = QtWidgets.QTabWidget(Reportes)
        self.tabWidget.setGeometry(QtCore.QRect(6, 9, 681, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Reportes)
        QtCore.QMetaObject.connectSlotsByName(Reportes)

    def retranslateUi(self, Reportes):
        _translate = QtCore.QCoreApplication.translate
        Reportes.setWindowTitle(_translate("Reportes", "Reportes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Reportes", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Reportes", "Tab 2"))
