# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rviqu\OneDrive - Universidad Internacional de las Américas (UIA)\UIA\2024\I\Programación II\Proyecto Final\tresPatitosUIA\src\004_departamentos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Departamentos(object):
    def setupUi(self, Departamentos):
        Departamentos.setObjectName("Departamentos")
        Departamentos.resize(481, 650)
        Departamentos.setMinimumSize(QtCore.QSize(480, 650))
        Departamentos.setMaximumSize(QtCore.QSize(500, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/iconMenuDepartamentos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Departamentos.setWindowIcon(icon)
        Departamentos.setToolTipDuration(1)
        Departamentos.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.lbl_departamentos = QtWidgets.QLabel(Departamentos)
        self.lbl_departamentos.setGeometry(QtCore.QRect(60, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(5)
        self.lbl_departamentos.setFont(font)
        self.lbl_departamentos.setStyleSheet("font: 43 10pt \"Segoe UI Semibold\";\n"
"border:none;\n"
"background-color: rgba(0,0,0,0%);")
        self.lbl_departamentos.setObjectName("lbl_departamentos")
        self.tblDepartamentos = QtWidgets.QTableWidget(Departamentos)
        self.tblDepartamentos.setGeometry(QtCore.QRect(40, 280, 410, 341))
        self.tblDepartamentos.setMinimumSize(QtCore.QSize(410, 320))
        self.tblDepartamentos.setMaximumSize(QtCore.QSize(1500, 1500))
        self.tblDepartamentos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tblDepartamentos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblDepartamentos.setAlternatingRowColors(True)
        self.tblDepartamentos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblDepartamentos.setWordWrap(False)
        self.tblDepartamentos.setRowCount(0)
        self.tblDepartamentos.setColumnCount(3)
        self.tblDepartamentos.setObjectName("tblDepartamentos")
        item = QtWidgets.QTableWidgetItem()
        self.tblDepartamentos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDepartamentos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDepartamentos.setHorizontalHeaderItem(2, item)
        self.splitter = QtWidgets.QSplitter(Departamentos)
        self.splitter.setGeometry(QtCore.QRect(40, 230, 311, 31))
        self.splitter.setStyleSheet("background-color: rgba(0,0,0,0%);")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btn_registrar = QtWidgets.QPushButton(self.splitter)
        self.btn_registrar.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid #55C1FA;\n"
"border-radius:10px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/btnSave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_registrar.setIcon(icon1)
        self.btn_registrar.setIconSize(QtCore.QSize(20, 20))
        self.btn_registrar.setObjectName("btn_registrar")
        self.btn_editar = QtWidgets.QPushButton(self.splitter)
        self.btn_editar.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid #55C1FA;\n"
"border-radius:10px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/btnEdit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_editar.setIcon(icon2)
        self.btn_editar.setIconSize(QtCore.QSize(20, 20))
        self.btn_editar.setObjectName("btn_editar")
        self.btn_eliminar = QtWidgets.QPushButton(self.splitter)
        self.btn_eliminar.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid #55C1FA;\n"
"border-radius:10px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/btnDelete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_eliminar.setIcon(icon3)
        self.btn_eliminar.setIconSize(QtCore.QSize(20, 20))
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.labelHeader = QtWidgets.QLabel(Departamentos)
        self.labelHeader.setGeometry(QtCore.QRect(20, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.labelHeader.setFont(font)
        self.labelHeader.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"background-color: rgba(0,0,0,0%);")
        self.labelHeader.setText("")
        self.labelHeader.setPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/iconDepartamentoHeader.png"))
        self.labelHeader.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelHeader.setObjectName("labelHeader")
        self.frame = QtWidgets.QFrame(Departamentos)
        self.frame.setGeometry(QtCore.QRect(40, 50, 401, 151))
        self.frame.setToolTip("")
        self.frame.setToolTipDuration(-1)
        self.frame.setStyleSheet("border:4px solid;\n"
"border-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_codigo = QtWidgets.QLabel(self.frame)
        self.lbl_codigo.setGeometry(QtCore.QRect(30, 20, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lbl_codigo.setFont(font)
        self.lbl_codigo.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"border:none;")
        self.lbl_codigo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_codigo.setObjectName("lbl_codigo")
        self.lbl_nombre = QtWidgets.QLabel(self.frame)
        self.lbl_nombre.setGeometry(QtCore.QRect(30, 60, 50, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lbl_nombre.setFont(font)
        self.lbl_nombre.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"border:none;")
        self.lbl_nombre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lbl_jefatura = QtWidgets.QLabel(self.frame)
        self.lbl_jefatura.setGeometry(QtCore.QRect(30, 100, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lbl_jefatura.setFont(font)
        self.lbl_jefatura.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"border:none;")
        self.lbl_jefatura.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_jefatura.setObjectName("lbl_jefatura")
        self.txt_codigo = QtWidgets.QLineEdit(self.frame)
        self.txt_codigo.setGeometry(QtCore.QRect(90, 22, 71, 20))
        self.txt_codigo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_codigo.setObjectName("txt_codigo")
        self.txt_nombre = QtWidgets.QLineEdit(self.frame)
        self.txt_nombre.setGeometry(QtCore.QRect(90, 61, 121, 20))
        self.txt_nombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_nombre.setObjectName("txt_nombre")
        self.cmb_jefatura = QtWidgets.QComboBox(self.frame)
        self.cmb_jefatura.setEnabled(True)
        self.cmb_jefatura.setGeometry(QtCore.QRect(90, 102, 121, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_jefatura.sizePolicy().hasHeightForWidth())
        self.cmb_jefatura.setSizePolicy(sizePolicy)
        self.cmb_jefatura.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_jefatura.setEditable(False)
        self.cmb_jefatura.setCurrentText("")
        self.cmb_jefatura.setObjectName("cmb_jefatura")
        self.lbl_codigo_2 = QtWidgets.QLabel(self.frame)
        self.lbl_codigo_2.setGeometry(QtCore.QRect(250, 40, 61, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_codigo_2.sizePolicy().hasHeightForWidth())
        self.lbl_codigo_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lbl_codigo_2.setFont(font)
        self.lbl_codigo_2.setStyleSheet("font: 63 10pt \"Segoe UI Semibold\";\n"
"border:none;\n"
"")
        self.lbl_codigo_2.setText("")
        self.lbl_codigo_2.setPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/assign2.png"))
        self.lbl_codigo_2.setScaledContents(True)
        self.lbl_codigo_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_codigo_2.setObjectName("lbl_codigo_2")
        self.btnNewCode = QtWidgets.QPushButton(self.frame)
        self.btnNewCode.setGeometry(QtCore.QRect(170, 21, 21, 21))
        self.btnNewCode.setToolTipDuration(0)
        self.btnNewCode.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid #55C1FA;\n"
"border-radius:10px;\n"
"}")
        self.btnNewCode.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/iconNewDoc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewCode.setIcon(icon4)
        self.btnNewCode.setObjectName("btnNewCode")
        self.btnLimpiar = QtWidgets.QPushButton(Departamentos)
        self.btnLimpiar.setGeometry(QtCore.QRect(360, 230, 81, 30))
        self.btnLimpiar.setMaximumSize(QtCore.QSize(90, 30))
        self.btnLimpiar.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid #55C1FA;\n"
"border-radius:10px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/btnClear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLimpiar.setIcon(icon5)
        self.btnLimpiar.setIconSize(QtCore.QSize(18, 18))
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.btnRefresh = QtWidgets.QPushButton(Departamentos)
        self.btnRefresh.setGeometry(QtCore.QRect(410, 20, 31, 23))
        self.btnRefresh.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px;\n"
"font: 63 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:2px solid #55C1FA;\n"
"border-radius:10px;\n"
"}")
        self.btnRefresh.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("c:\\Users\\rviqu\\OneDrive - Universidad Internacional de las Américas (UIA)\\UIA\\2024\\I\\Programación II\\Proyecto Final\\tresPatitosUIA\\src\\../res/icons8-refresh-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRefresh.setIcon(icon6)
        self.btnRefresh.setShortcut("")
        self.btnRefresh.setObjectName("btnRefresh")

        self.retranslateUi(Departamentos)
        QtCore.QMetaObject.connectSlotsByName(Departamentos)

    def retranslateUi(self, Departamentos):
        _translate = QtCore.QCoreApplication.translate
        Departamentos.setWindowTitle(_translate("Departamentos", "Departamentos"))
        self.lbl_departamentos.setText(_translate("Departamentos", "Administración de Departamentos"))
        self.tblDepartamentos.setSortingEnabled(True)
        item = self.tblDepartamentos.horizontalHeaderItem(0)
        item.setText(_translate("Departamentos", "Código"))
        item = self.tblDepartamentos.horizontalHeaderItem(1)
        item.setText(_translate("Departamentos", "Nombre"))
        item = self.tblDepartamentos.horizontalHeaderItem(2)
        item.setText(_translate("Departamentos", "Jefatura"))
        self.btn_registrar.setToolTip(_translate("Departamentos", "CTRL+S"))
        self.btn_registrar.setText(_translate("Departamentos", "Registrar"))
        self.btn_registrar.setShortcut(_translate("Departamentos", "Ctrl+C"))
        self.btn_editar.setToolTip(_translate("Departamentos", "CTRL+E"))
        self.btn_editar.setText(_translate("Departamentos", "Modificar"))
        self.btn_editar.setShortcut(_translate("Departamentos", "Ctrl+E"))
        self.btn_eliminar.setToolTip(_translate("Departamentos", "CTRL+DEL"))
        self.btn_eliminar.setText(_translate("Departamentos", "Eliminar"))
        self.btn_eliminar.setShortcut(_translate("Departamentos", "Ctrl+Del"))
        self.frame.setAccessibleDescription(_translate("Departamentos", "Generar código"))
        self.lbl_codigo.setText(_translate("Departamentos", "Código"))
        self.lbl_nombre.setText(_translate("Departamentos", "Nombre"))
        self.lbl_jefatura.setText(_translate("Departamentos", "Jefatura"))
        self.btnNewCode.setToolTip(_translate("Departamentos", "Auto rellenar"))
        self.btnLimpiar.setToolTip(_translate("Departamentos", "CTRL+W"))
        self.btnLimpiar.setText(_translate("Departamentos", "Limpiar"))
        self.btnLimpiar.setShortcut(_translate("Departamentos", "Ctrl+W"))
        self.btnRefresh.setToolTip(_translate("Departamentos", "CTRL+R"))
