# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rviqu\OneDrive - Universidad Internacional de las Américas (UIA)\UIA\2024\I\Programación II\Proyecto Final\tresPatitosUIA\src\mdi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mdiWindow(object):
    def setupUi(self, mdiWindow):
        mdiWindow.setObjectName("mdiWindow")
        mdiWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mdiWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(-1, -1, 801, 581))
        self.mdiArea.setObjectName("mdiArea")
        mdiWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mdiWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuLogin = QtWidgets.QMenu(self.menubar)
        self.menuLogin.setObjectName("menuLogin")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.mniBienes = QtWidgets.QMenu(self.menuMenu)
        self.mniBienes.setObjectName("mniBienes")
        mdiWindow.setMenuBar(self.menubar)
        self.mniUsuarios = QtWidgets.QAction(mdiWindow)
        self.mniUsuarios.setObjectName("mniUsuarios")
        self.mniEmpleados = QtWidgets.QAction(mdiWindow)
        self.mniEmpleados.setObjectName("mniEmpleados")
        self.mniDepartamentos = QtWidgets.QAction(mdiWindow)
        self.mniDepartamentos.setObjectName("mniDepartamentos")
        self.mniAsignar = QtWidgets.QAction(mdiWindow)
        self.mniAsignar.setObjectName("mniAsignar")
        self.mniDesligar = QtWidgets.QAction(mdiWindow)
        self.mniDesligar.setObjectName("mniDesligar")
        self.actionLogin = QtWidgets.QAction(mdiWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.menuLogin.addAction(self.actionLogin)
        self.mniBienes.addAction(self.mniAsignar)
        self.mniBienes.addAction(self.mniDesligar)
        self.menuMenu.addAction(self.mniUsuarios)
        self.menuMenu.addAction(self.mniEmpleados)
        self.menuMenu.addAction(self.mniDepartamentos)
        self.menuMenu.addAction(self.mniBienes.menuAction())
        self.menubar.addAction(self.menuLogin.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(mdiWindow)
        QtCore.QMetaObject.connectSlotsByName(mdiWindow)

    def retranslateUi(self, mdiWindow):
        _translate = QtCore.QCoreApplication.translate
        mdiWindow.setWindowTitle(_translate("mdiWindow", "MainWindow"))
        self.menuLogin.setTitle(_translate("mdiWindow", "Login"))
        self.menuMenu.setTitle(_translate("mdiWindow", "Menu"))
        self.mniBienes.setTitle(_translate("mdiWindow", "Bienes"))
        self.mniUsuarios.setText(_translate("mdiWindow", "Usuarios"))
        self.mniEmpleados.setText(_translate("mdiWindow", "Empleados"))
        self.mniDepartamentos.setText(_translate("mdiWindow", "Departamentos"))
        self.mniAsignar.setText(_translate("mdiWindow", "Asignar"))
        self.mniDesligar.setText(_translate("mdiWindow", "Desligar"))
        self.actionLogin.setText(_translate("mdiWindow", "Login"))
