# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rviqu\OneDrive - Universidad Internacional de las Américas (UIA)\UIA\2024\I\Programación II\Proyecto Final\tresPatitosUIA\src\mdi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mdiWindow(object):
    def setupUi(self, mdiWindow):
        mdiWindow.setObjectName("mdiWindow")
        mdiWindow.resize(607, 394)
        self.centralwidget = QtWidgets.QWidget(mdiWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 611, 361))
        self.mdiArea.setObjectName("mdiArea")
        mdiWindow.setCentralWidget(self.centralwidget)
        self.mnubar = QtWidgets.QMenuBar(mdiWindow)
        self.mnubar.setGeometry(QtCore.QRect(0, 0, 607, 21))
        self.mnubar.setObjectName("mnubar")
        self.mnuUsuarios = QtWidgets.QMenu(self.mnubar)
        self.mnuUsuarios.setObjectName("mnuUsuarios")
        self.mnuEmpleados = QtWidgets.QMenu(self.mnubar)
        self.mnuEmpleados.setObjectName("mnuEmpleados")
        self.mnuDepartamentos = QtWidgets.QMenu(self.mnubar)
        self.mnuDepartamentos.setObjectName("mnuDepartamentos")
        self.mnuBienes = QtWidgets.QMenu(self.mnubar)
        self.mnuBienes.setObjectName("mnuBienes")
        self.mnuReportes = QtWidgets.QMenu(self.mnubar)
        self.mnuReportes.setObjectName("mnuReportes")
        self.mnuLogin = QtWidgets.QMenu(self.mnubar)
        self.mnuLogin.setObjectName("mnuLogin")
        mdiWindow.setMenuBar(self.mnubar)
        self.statusbar = QtWidgets.QStatusBar(mdiWindow)
        self.statusbar.setObjectName("statusbar")
        mdiWindow.setStatusBar(self.statusbar)
        self.mniAsignar = QtWidgets.QAction(mdiWindow)
        self.mniAsignar.setObjectName("mniAsignar")
        self.mniDesligar = QtWidgets.QAction(mdiWindow)
        self.mniDesligar.setObjectName("mniDesligar")
        self.mniBienes = QtWidgets.QAction(mdiWindow)
        self.mniBienes.setObjectName("mniBienes")
        self.mnuBienes.addAction(self.mniAsignar)
        self.mnuBienes.addAction(self.mniDesligar)
        self.mnuBienes.addAction(self.mniBienes)
        self.mnubar.addAction(self.mnuLogin.menuAction())
        self.mnubar.addAction(self.mnuUsuarios.menuAction())
        self.mnubar.addAction(self.mnuEmpleados.menuAction())
        self.mnubar.addAction(self.mnuDepartamentos.menuAction())
        self.mnubar.addAction(self.mnuBienes.menuAction())
        self.mnubar.addAction(self.mnuReportes.menuAction())

        self.retranslateUi(mdiWindow)
        QtCore.QMetaObject.connectSlotsByName(mdiWindow)

    def retranslateUi(self, mdiWindow):
        _translate = QtCore.QCoreApplication.translate
        mdiWindow.setWindowTitle(_translate("mdiWindow", "MainWindow"))
        self.mnuUsuarios.setTitle(_translate("mdiWindow", "Usuarios"))
        self.mnuEmpleados.setTitle(_translate("mdiWindow", "Empleados"))
        self.mnuDepartamentos.setTitle(_translate("mdiWindow", "Departamento"))
        self.mnuBienes.setTitle(_translate("mdiWindow", "Bienes"))
        self.mnuReportes.setTitle(_translate("mdiWindow", "Reportes"))
        self.mnuLogin.setTitle(_translate("mdiWindow", "Log In"))
        self.mniAsignar.setText(_translate("mdiWindow", "Asiganción de bienes"))
        self.mniDesligar.setText(_translate("mdiWindow", "Desligar Bienes"))
        self.mniBienes.setText(_translate("mdiWindow", "Bienes"))
